### ISSUE TITLE
Version of protobuf

### ISSUE THREAD

**Issue by amuse38** [topobyte/osm4j-pbf#1]
Hi,

I'm using your wonderful libraries with Protobuf also.
Anyway, I'm interested in using the "oneof" feature of the version 2.6.1 of protobuf but I'm facing some issues as it is impossible to mix two different versions of Protobuf at the same time.

Please, if would you mind using the most recent version of protobuf ?

Many thanks for your help,

Best regards,

Alain

**Comment by sebkur** [comment]
Good point. I have upgraded to protobuf 2.6.1 and regenerated the source code so that it compiles with that version of the library.

Just update your build file to use osm4j-pbf version 0.0.6 to use the new version.

**Comment by amuse38** [comment]
Hi, 

Many thanks for your help and responsiveness ! 

Best regards, 

Alain 

----- Mail original -----

De: "Sebastian" notifications@github.com 
À: "topobyte/osm4j-pbf" osm4j-pbf@noreply.github.com 
Cc: "Alain MUSE" alain.muse@laposte.net 
Envoyé: Jeudi 14 Janvier 2016 00:56:42 
Objet: Re: [osm4j-pbf] Version of protobuf (#1) 

Good point. I have upgraded to protobuf 2.6.1 and regenerated the source code so that it compiles with that version of the library. 

Just update your build file to use osm4j-pbf version 0.0.6 to use the new version.

**Comment by hklarner** [comment]
see also https://github.com/topobyte/osm4j-pbf/issues/8
