### ISSUE TITLE
Discrepancy between geometry produced by osm4j and the original osm one

### ISSUE THREAD

**Issue by lorenaqendro** [topobyte/osm4j-pbf#7]
### Versions

| Software | Information |
| :--- | :--- |
| Operating System| OS X El Capitan|
| OS Version| e.g. `10.11.6` |
| java -version | e.g. `1.8.0_121` | 
### Description
When using osm4j I notice a discrepancy between the geometry provided by it and the original from osm. As you can see in the screenshot they differ. It happens with all the shapes and the overlapping between them never matches.

### Error log
This is a screenshot I took when opening the pbf from geofabrik and the result from osm4j on QGIS. The green is from osm4j and the brown the original.

<img width="1156" alt="screen shot 2018-05-08 at 12 32 35" src="https://user-images.githubusercontent.com/14051876/39993276-2a84760e-576d-11e8-917d-02f5a20d0010.png">

**Comment by sebkur** [comment]
Looks to me like there may be some simplification going on with the data produced using osm4j. Could you share he OSM object id of the geometry rendered in the image?

**Comment by lorenaqendro** [comment]
I lost track of this object but I produced another one. The blue is osm instead the brown mine using osm4j. Id and tags as in picture 2.

<img width="876" alt="screen shot 2018-05-15 at 11 39 39" src="https://user-images.githubusercontent.com/14051876/40052257-641fe47a-5835-11e8-80d8-6f3c79352c96.png">

<img width="877" alt="screen shot 2018-05-15 at 11 41 53" src="https://user-images.githubusercontent.com/14051876/40052256-6409a14c-5835-11e8-8a26-c91e5eda6604.png">

**Comment by sebkur** [comment]
Okay, by viewing the object on OSM directly, I can confirm that the blue result is what is to be expected:
https://www.openstreetmap.org/way/477546559

**Comment by sebkur** [comment]
However, I can also produce the correct result using osm4j. See this minimal example for building the mentioned way:

	public static void main(String[] args)
			throws IOException, EntityNotFoundException
	{
		String query = "http://overpass-api.de/api/interpreter?data=(way(477546559);>;);out;";

		// Open a stream
		InputStream input = new URL(query).openStream();

		OsmIterator iterator = new OsmXmlIterator(input, false);
		InMemoryMapDataSet data = MapDataSetLoader.read(iterator, false, false,
				true);

		TLongObjectMap<OsmWay> ways = data.getWays();

		if (ways.isEmpty()) {
			System.out.println("No way found");
			return;
		}

		OsmWay way = ways.valueCollection().iterator().next();

		RegionBuilder rb = new RegionBuilder();
		RegionBuilderResult result = rb.build(way, data);
		Geometry polygon = result.getMultiPolygon();

		Map<String, String> tags = OsmModelUtil.getTagsAsMap(way);
		Map<String, Object> properties = new HashMap<>();
		for (String key : tags.keySet()) {
			properties.put(key, tags.get(key));
		}

		GeoJSONWriter writer = new GeoJSONWriter();
		org.wololo.geojson.Geometry g = writer.write(polygon);
		Feature feature = new Feature(g, properties);

		String json = feature.toString();

		System.out.println(GeoJsonHelper.prettyPrintFeature(json));
	}

Here's the result:

    {
      "type" : "Feature",
      "properties" : { },
      "geometry" : {
        "type" : "MultiPolygon",
        "coordinates" : [ [ [ [ -0.4826313, 51.8447067 ], [ -0.4825535, 51.8449718 ], [ -0.4821727, 51.8453214 ], [ -0.4816657, 51.8452104 ], [ -0.4809791, 51.845048 ], [ -0.4812956, 51.8444863 ], [ -0.4813787, 51.8444167 ], [ -0.4820332, 51.8445227 ], [ -0.4825938, 51.8446569 ], [ -0.4826313, 51.8447067 ] ] ] ]
      }
    }

Copy it to [geojson.io](http://geojson.io) to verify the result.

**Comment by sebkur** [comment]
If you can point me to the source code where you're using osm4j, I might get a clue what's going on. Still my hunch is a simplification taking place for some reason. Also it could be due to an optional `GeometryFactory` instance passed to osm4j's geometry builder; the `GeometryFactory` from JTS can be configured to reduce precision or snap to a coordinate grid.

**Comment by lorenaqendro** [comment]
I use it in [this class](https://github.com/FutureCitiesCatapult/TomboloDigitalConnector/blob/master/src/main/java/uk/org/tombolo/importer/osm/OSMEntityHandler.java). I've tried different scales for `PrecisionModel` when creating the `GeometryFactory`, but the issue persisted.

**Comment by sebkur** [comment]
I don't see anything suspicious in that code. However, I'm not really able to test the code myself, I tried setting up `FutureCitiesCatapult/TomboloDigitalConnector` for testing before but didn't want to set up a local database. I think to find out what's going on, we need to reduce complexity to get to the heart of the problem. Next thing I would do is make sure the problem is already present right after building the geometry by printing it to the console and viewing the result on geojson.io. I would add this code:

    public void handle(OsmWay way) {
    ...
        if (way.getId() == 477546559) {
             GeoJSONWriter writer = new GeoJSONWriter();
             org.wololo.geojson.Geometry g = writer.write(osmGeometry);
             Map<String, Object> properties = new HashMap<>();
             Feature feature = new Feature(g, properties);
             String json = feature.toString();
             System.out.println(json);
         }
    ...
    }

**Comment by lorenaqendro** [comment]
Seems like the discrepancy is caused on our side because of cutting/rounding up the coordinates to 4 decimal places in geometry json object we create. I’ll close this issue after a few other tests on different geometry types so we can be sure about it. Thanks again!

**Comment by lorenaqendro** [comment]
Closing this issue as investigation showed it was not caused by osm4j. Cheers!
